<img src="TechLabs.png">

<h2>Please enter your full name here: Hugo Remy</h2>


<p> This exam will test your knowledge in Artificial Intelligence. </p>
<p> We will test the following: </p>

- Logistic Regressions
- Neural Networks
- Monte Carlo Simulation

# Question 1:
Below is the code to import a standard dataset with breast cancer.
When you run the cell, you will have it stored as the object "data",
and the description of the dataset is printed out for you.

### Your task is to create two models for classifying the diagnosis, and compare the accuracy metrics for the two:
### 1. a) Logistic Regression: 
"sklearn.linear_model" offers good logit classifiers. Because the dataset is fairly small (~500 rows), we suggest that you use the "liblinear" solver for fitting the logit classifier.

Split the dataset into a test and training (30% test / 70% training) dataset and train the model on the training dataset. Then, classify the test dataset, and compute the accuracy, which you can print as an output.

P.S.: We do not expect you to regularize for type 1 or type 2 errors. Your goal is to build models that classify well the diagnosis. Also, we do not expect you to spend hours on feature engineering and/or other things that may or may not improve testing accuracy. A good answer shall just contain a sensible model and the testing accuracy.

In [2]:
import numpy as np

from sklearn import datasets
data = datasets.load_breast_cancer()
print(np.shape(data.data))

(569, 30)


In [3]:
print(data.DESCR)

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        worst/largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 0 is Mean Radi

In [4]:
print(data.data)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [40]:
print(data.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 0 0 0 1 1
 1 1 0 1 0 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 0 0
 0 1 0 0 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1
 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 0 1 0 1 1 1 1 1 0 1 1
 0 1 0 1 1 0 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 1
 1 1 1 1 1 1 0 1 0 1 1 0 

In [5]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(data.data, data.target, train_size = 0.7, test_size = 0.3)

In [7]:
print(np.shape(X_train))

(398, 30)


In [8]:
print(np.shape(X_test))

(171, 30)


In [9]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

In [10]:
model = LogisticRegression(solver='liblinear', random_state=0)

In [11]:
model.fit(X_train, Y_train)

LogisticRegression(random_state=0, solver='liblinear')

In [12]:
Y_pred = model.predict(X_test)

In [85]:
cm = confusion_matrix(Y_test, Y_pred)
cm

array([[ 59,   6],
       [  4, 102]])

In [86]:
logitacc = (cm[0][0] + cm[1][1])/(cm[0][0]+cm[0][1]+cm[1][0]+cm[1][1])
logitacc

0.9415204678362573

# Print the logit accuracy below:

In [87]:
logitacc = "94.2%"
print(f"\ntesting set accuracy with logit is: {logitacc}")


testing set accuracy with logit is: 94.2%


### 1. b) Feedforward Neural Network:
So far, so good. Let's see how a feedforward neural network does for the same task.

Take the same train/test split as in a), and construct the following neural network, which you fit to the data:

In [43]:
import pickle
pickle.loads(b'\x80\x03]q\x00(X\x15\x00\x00\x00Model: "sequential_2"q\x01XA\x00\x00\x00_________________________________________________________________q\x02XA\x00\x00\x00Layer (type)                 Output Shape              Param #   q\x03XA\x00\x00\x00=================================================================q\x04XA\x00\x00\x00dense_5 (Dense)              (None, 30)                930       q\x05XA\x00\x00\x00_________________________________________________________________q\x06XA\x00\x00\x00dense_6 (Dense)              (None, 50)                1550      q\x07XA\x00\x00\x00_________________________________________________________________q\x08XA\x00\x00\x00dense_7 (Dense)              (None, 30)                1530      q\tXA\x00\x00\x00_________________________________________________________________q\nXA\x00\x00\x00dense_8 (Dense)              (None, 1)                 31        q\x0bXA\x00\x00\x00=================================================================q\x0cX\x13\x00\x00\x00Total params: 4,041q\rX\x17\x00\x00\x00Trainable params: 4,041q\x0eX\x17\x00\x00\x00Non-trainable params: 0q\x0fXA\x00\x00\x00_________________________________________________________________q\x10e.')

['Model: "sequential_2"',
 '_________________________________________________________________',
 'Layer (type)                 Output Shape              Param #   ',
 '=================================================================',
 'dense_5 (Dense)              (None, 30)                930       ',
 '_________________________________________________________________',
 'dense_6 (Dense)              (None, 50)                1550      ',
 '_________________________________________________________________',
 'dense_7 (Dense)              (None, 30)                1530      ',
 '_________________________________________________________________',
 'dense_8 (Dense)              (None, 1)                 31        ',
 '=================================================================',
 'Total params: 4,041',
 'Trainable params: 4,041',
 'Non-trainable params: 0',
 '_________________________________________________________________']

### You can use the library keras to contruct the ANN. Since we are dealing with a classification problem, we recommend binary_crossentropy as a loss function.
Choose a reasonable batch size and epoch count and train the model.
### Here again, print the testing dataset accuracy:

In [26]:
!pip install keras
!pip install tensorflow

     |████████████████████████████████| 173.9 MB 2.0 kB/s  eta 0:00:01
     |████████████████████████████████| 3.3 MB 3.7 MB/s eta 0:00:01
     |████████████████████████████████| 127 kB 10.9 MB/s eta 0:00:01
     |████████████████████████████████| 42 kB 2.3 MB/s  eta 0:00:01
     |████████████████████████████████| 65 kB 6.8 MB/s  eta 0:00:01
     |████████████████████████████████| 10.6 MB 12.7 MB/s eta 0:00:01
     |████████████████████████████████| 15.6 MB 9.1 MB/s eta 0:00:01
     |████████████████████████████████| 1.0 MB 16.1 MB/s eta 0:00:01
     |████████████████████████████████| 462 kB 15.0 MB/s eta 0:00:01
     |████████████████████████████████| 57 kB 8.2 MB/s  eta 0:00:01
     |████████████████████████████████| 781 kB 3.7 MB/s eta 0:00:01
     |████████████████████████████████| 135 kB 9.9 MB/s eta 0:00:01
     |████████████████████████████████| 97 kB 7.3 MB/s  eta 0:00:01
     |████████████████████████████████| 155 kB 12.0 MB/s eta 0:00:01
     |████████████████████████████████

In [27]:
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout

In [52]:
# Initialising the ANN
classifier = Sequential()

In [68]:
#Adding Layers to the model
classifier.add(Dense(30, activation='sigmoid'))
classifier.add(Dropout(0.25))
classifier.add(Dense(50, activation='sigmoid'))
classifier.add(Dropout(0.25))
classifier.add(Dense(30, activation='sigmoid'))
classifier.add(Dropout(0.25))
classifier.add(Dense(1, activation='sigmoid'))
classifier.add(Dropout(0.25))

In [69]:
# Compiling the ANN
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [70]:
# Fitting the ANN to the Training set
classifier.fit(X_train, Y_train, batch_size=50, epochs=500, verbose=1, validation_data=(X_test, Y_test))

Epoch 1/500
8/8 [==============================] - 1s 26ms/step - loss: 3.5353 - accuracy: 0.5588 - val_loss: 0.6706 - val_accuracy: 0.6199
Epoch 2/500
8/8 [==============================] - 0s 6ms/step - loss: 2.8797 - accuracy: 0.5443 - val_loss: 0.6962 - val_accuracy: 0.3801
Epoch 3/500
8/8 [==============================] - 0s 7ms/step - loss: 2.6459 - accuracy: 0.5331 - val_loss: 0.7224 - val_accuracy: 0.3801
Epoch 4/500
8/8 [==============================] - 0s 7ms/step - loss: 3.2423 - accuracy: 0.5151 - val_loss: 0.7346 - val_accuracy: 0.3801
Epoch 5/500
8/8 [==============================] - 0s 7ms/step - loss: 2.9211 - accuracy: 0.4958 - val_loss: 0.7378 - val_accuracy: 0.3801
Epoch 6/500
8/8 [==============================] - 0s 7ms/step - loss: 3.2026 - accuracy: 0.4915 - val_loss: 0.7390 - val_accuracy: 0.3801
Epoch 7/500
8/8 [==============================] - 0s 6ms/step - loss: 3.1230 - accuracy: 0.5252 - val_loss: 0.7371 - val_accuracy: 0.3801
Epoch 8/500
8/8 [=========

In [79]:
Y_pred_ANN = classifier.predict(X_test)
Y_pred_ANN = (Y_pred_ANN > 0.5)

In [88]:
cm_ANN = confusion_matrix(Y_test, Y_pred_ANN)
cm_ANN

array([[62,  3],
       [18, 88]])

In [89]:
ANNacc = (cm_ANN[0][0] + cm_ANN[1][1])/(cm_ANN[0][0]+cm_ANN[0][1]+cm_ANN[1][0]+cm_ANN[1][1])
ANNacc

0.8771929824561403

In [90]:
ANNacc = "87.7%"
print(f"\ntesting set accuracy with logit is: {ANNacc}")


testing set accuracy with logit is: 87.7%


### 1. c) Compare the performance of the neural net with the logit. Which one seems better at the job and why might that be?
Please also comment on which model you would choose to implement in a case like this and why.

In [93]:
"Here logitacc > ANNacc suggesting that the logistic regression seems better at the job than the neural network. Normally, a neural network is always better than logistic regression for binary classification, or can do no worse. Here it is not the case because we did not prepare the ANN as we should have and went directly for the classifier. Things we could have done to obtain a better performance at the ANN are encoding categorical data, feature scaling, data normalization, feature engineering etc."

'Here logitacc > ANNacc suggesting that the logistic regression seems better at the job than the neural network. Normally, a neural network is always better than logistic regression for binary classification, or can do no worse. Here it is not the case because we did not prepare the ANN as we should have and went directly for the classifier. Things we could have done to obtain a better performance at the ANN are encoding categorical data, feature scaling, data normalization, feature engineering etc.'

# Question 2:
### Your coding skills have gained you a job as an options trader at a successful hedge fund! Congratulations!!

At the first day, your boss comes to you and asks you, whether he should buy a _call option_* with a certain set of characteristics for 1€.

    *A call option gives you the right (but not obligation) to buy a share for a certain strike price. In other words, if the stock price is higher than the strike price, you get the difference, otherwise, you get 0: 
    
    callpayoff = max(stockprice - strikeprice, 0) 

To price the option, you shall build a monte-carlo simulator which generatates _1 000 000_ random walks, each representing the stock price in one year, which is when the option can be expired. By taking the average of these payouts, you will get the expected payout at expiry!

Luckily, your boss has also given you the characteristics and hints for how the stock price moves: 

The stock price follows a student T distribution with 3 degrees of freedom (the rvs function within the t class from scipy.stats package is a great tool for creating random walks with this distribution: https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.t.html  ctrl+f "rvs") 

- The stock price today: 69
- Stock returns follow student T distribution with 3 degrees of freedom
- drift of 10% per year 
- volatility of 20%
- strike price of the option is 96

### Build a function that returns the price of the call option, and shows your boss what payout he can expect from the option in order to explain him, whether he should buy it or not.

    P.S.: If you run into trouble on your way, you can always ask for tips from your boss and since he is a nice guy, he will also give a good grade for all attempts!

In [95]:
import math
from numpy import *
from time import time
# star import for shorter code
random.seed(20000)
t0 = time()
# Parameters
S0 = 69.; K = 96.; T = 1.0; r = 0.1; sigma = 0.2
M = 50; dt = T / M; I = 1000000
# Simulating I paths with M time steps
S = S0 * exp(cumsum((r - 0.5 * sigma ** 2) * dt
+ sigma * math.sqrt(dt)
* random.standard_normal((M + 1, I)), axis=0))
# sum instead of cumsum would also do
# if only the final values are of interest
S[0] = S0
# Calculating the Monte Carlo estimator
C0 = math.exp(-r * T) * sum(maximum(S[-1] - K, 0)) / I
# Results output
tnp2 = time() - t0

print('The European Option Value is: ', C0)  

The European Option Value is:  1.0074529415147335


# Good luck!

Don't forget: google, github and stack overflow are your best friends!
